task:
    path: /
    controller: App\Controller\TaskController::index

task_detail:
    path: /task/detail/{id}
    controller: App\Controller\TaskController::detail

delete:
    path: /task/delete/{id}
    controller: App\Controller\TaskController::delete

task_edit:
    path: /task/edit/{id}
    controller: App\Controller\TaskController::edit


my_task:
    path: /task/My
    controller: App\Controller\TaskController::myTasks

creation: 
    path: /task/creation
    controller: App\Controller\TaskController::creation

    
register:
    path: /registro
    controller: App\Controller\UserController::register

login: 
    path: /login
    controller: App\Controller\UserController::login

logout:
    path: /logout


    
